name: Continuous integration for languages
on:
  push:
    branches: [main]
    paths:
      - 'languages/**'
  pull_request:
    paths:
      - 'languages/**'
  schedule:
    - cron: "0 0 1,15 * *"

jobs:
  list-languages:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: languages
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: List langauges
        id: language-list
        run: echo "languages=$(find -mindepth 1 -maxdepth 1 -type d | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
    outputs:
      languages: ${{ steps.language-list.outputs.languages }}

  test-languages:
    needs: list-languages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ${{ fromJson(needs.list-languages.outputs.languages) }}
    defaults:
      run:
        working-directory: languages/${{ matrix.language }}
    steps:
      - name: Install Node environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
